# Generated by Django 4.2.23 on 2025-08-04 20:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0002_emailattachment_templateattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=ckeditor.fields.RichTextField(help_text='Use the toolbar above for rich text formatting including bold, italic, colors, lists, and more.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_html',
            field=models.BooleanField(default=True, help_text='Automatically set to True when using rich text editor'),
        ),
    ]
