# Generated by Django 4.2.23 on 2025-08-04 20:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0003_alter_emailtemplate_body_alter_emailtemplate_is_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=ckeditor.fields.RichTextField(help_text='Use the rich text editor to format your email content with bold, italic, lists, links, etc.'),
        ),
    ]
