# Generated by Django 4.2.23 on 2025-08-04 20:39

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0004_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Use the rich text editor to format your email content with bold, italic, lists, links, etc.'),
        ),
    ]
