# Generated by Django 4.2.23 on 2025-08-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0005_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipient',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(blank=True, help_text='Display name', max_length=200),
        ),
    ]
