# Generated by Django 4.2.23 on 2025-08-04 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_api', '0006_recipient_first_name_recipient_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('interval', models.CharField(choices=[('once', 'Send Once'), ('hourly', 'Every Hour'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=20)),
                ('scheduled_datetime', models.DateTimeField(help_text='When to start sending emails')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='When to stop recurring emails (optional)', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, to='email_api.recipient')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_api.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
