# Generated by Django 4.2.23 on 2025-08-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0008_sequentialemailcampaign_sequentialemailrecipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequentialemailcampaign',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='sequentialemailcampaign',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date to start sending emails', null=True),
        ),
        migrations.AddField(
            model_name='sequentialemailcampaign',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Time to start sending the first email', null=True),
        ),
    ]
